version: "3.9"

services:

  nginx:
    build: ./nginx
    ports:
      - 8900:8080
    restart: always
  
  golang:
    build: ./golang
    ports:
      - 3061:3061
  
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
    restart: always
      
networks:
  my-service:
    external: true
    
  