version: "3.9"

services:

  nginx:
    container_name: D.F.B.nginx
    build: ./nginx
    ports:
      - 80:80
    restart: always
  
  golang:
    container_name: D.F.B.golang
    build: ./golang
    ports:
      - 3061:3061
  
  node:
    container_name: D.F.B.node
    build: ./node
    ports:
      - 3060:3060

  redis:
    container_name: D.F.B.redis
    image: "redis:latest"
    ports:
      - 6379:6379
    restart: always
      
networks:
  my-service:
    external: true
    
  